[package]
name = "crossflow"
version = "0.1.0"
description = "CrossFlow devnet contract scaffold"
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
name = "crossflow"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build", "anchor-spl/token_2022"]
anchor-debug = []
custom-heap = []
custom-panic = []


[dependencies]
anchor-lang = { version = "=1.1.2", features = ["init-if-needed"] }
anchor-spl = { version = "=1.1.2", default-features = false, features = ["token", "associated_token"] }
solana-sha256-hasher = { version = "=3.1.0", features = ["sha2"] }
solana-instructions-sysvar = "=3.0.1"

[build-dependencies]
bs58 = "=0.5.1"
serde_json = "=1.0.151"
sha2 = "=0.10.9"
solana-pubkey = { version = "=3.0.0", features = ["curve25519"] }

[dev-dependencies]
litesvm = "=0.10.0"
solana-message = "=3.0.1"
solana-transaction = "=3.0.2"
solana-signer = "=3.0.0"
solana-keypair = "=3.1.0"


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
